set_pns_commit_mode true
# Starting to commit core rings
# Starting to commit block rings
# Starting to commit metal5 straps for net VDD
create_power_straps  -direction vertical  -start_at 13.190 -nets VDD  -layer 35 -width 2.260 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 24.950 -nets VDD  -layer 35 -width 2.260 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 36.710 -nets VDD  -layer 35 -width 2.260 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 48.470 -nets VDD  -layer 35 -width 2.260 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 60.245 -nets VDD  -layer 35 -width 2.230 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 72.270 -nets VDD  -layer 35 -width 2.260 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 84.030 -nets VDD  -layer 35 -width 2.260 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 107.550 -nets VDD  -layer 35 -width 2.260 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 119.590 -nets VDD  -layer 35 -width 2.260 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 131.350 -nets VDD  -layer 35 -width 2.260 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 143.110 -nets VDD  -layer 35 -width 2.260 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 154.870 -nets VDD  -layer 35 -width 2.260 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 166.630 -nets VDD  -layer 35 -width 2.260 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 178.670 -nets VDD  -layer 35 -width 2.260 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 190.725 -nets VDD  -layer 35 -width 1.670 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 202.190 -nets VDD  -layer 35 -width 2.260 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 213.950 -nets VDD  -layer 35 -width 2.260 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 237.750 -nets VDD  -layer 35 -width 2.260 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 249.510 -nets VDD  -layer 35 -width 2.260 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 261.270 -nets VDD  -layer 35 -width 2.260 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 273.030 -nets VDD  -layer 35 -width 2.260 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 285.070 -nets VDD  -layer 35 -width 2.260 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 296.830 -nets VDD  -layer 35 -width 2.260 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 308.590 -nets VDD  -layer 35 -width 2.260 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 320.990 -nets VDD  -layer 35 -width 1.300 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 332.110 -nets VDD  -layer 35 -width 2.260 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 344.150 -nets VDD  -layer 35 -width 2.260 -pitch_within_group 11.820 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 350.120 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal6 straps for net VDD
create_power_straps  -direction horizontal  -start_at 13.970 -nets VDD  -layer 36 -width 2.400 -pitch_within_group 11.640 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 353.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 25.730 -nets VDD  -layer 36 -width 2.400 -pitch_within_group 11.640 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 353.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 37.210 -nets VDD  -layer 36 -width 2.400 -pitch_within_group 11.640 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 353.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 48.970 -nets VDD  -layer 36 -width 2.400 -pitch_within_group 11.640 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 353.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 60.690 -nets VDD  -layer 36 -width 1.920 -pitch_within_group 11.640 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 353.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 72.210 -nets VDD  -layer 36 -width 2.400 -pitch_within_group 11.640 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 353.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 83.970 -nets VDD  -layer 36 -width 2.400 -pitch_within_group 11.640 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 353.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 107.210 -nets VDD  -layer 36 -width 2.400 -pitch_within_group 11.640 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 353.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 118.690 -nets VDD  -layer 36 -width 2.400 -pitch_within_group 11.640 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 353.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 141.930 -nets VDD  -layer 36 -width 2.400 -pitch_within_group 11.640 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 353.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 153.690 -nets VDD  -layer 36 -width 2.400 -pitch_within_group 11.640 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 353.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 165.450 -nets VDD  -layer 36 -width 2.400 -pitch_within_group 11.640 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 353.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 176.930 -nets VDD  -layer 36 -width 2.400 -pitch_within_group 11.640 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 353.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 189.070 -nets VDD  -layer 36 -width 1.640 -pitch_within_group 11.640 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 353.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 200.170 -nets VDD  -layer 36 -width 2.400 -pitch_within_group 11.640 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 353.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 211.930 -nets VDD  -layer 36 -width 2.400 -pitch_within_group 11.640 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 353.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 235.170 -nets VDD  -layer 36 -width 2.400 -pitch_within_group 11.640 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 353.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 246.930 -nets VDD  -layer 36 -width 2.400 -pitch_within_group 11.640 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 353.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 258.410 -nets VDD  -layer 36 -width 2.400 -pitch_within_group 11.640 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 353.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 270.170 -nets VDD  -layer 36 -width 2.400 -pitch_within_group 11.640 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 353.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 281.650 -nets VDD  -layer 36 -width 2.400 -pitch_within_group 11.640 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 353.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 293.410 -nets VDD  -layer 36 -width 2.400 -pitch_within_group 11.640 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 353.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 304.890 -nets VDD  -layer 36 -width 2.400 -pitch_within_group 11.640 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 353.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 317.430 -nets VDD  -layer 36 -width 0.920 -pitch_within_group 11.640 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 353.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 328.410 -nets VDD  -layer 36 -width 2.400 -pitch_within_group 11.640 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 353.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 339.890 -nets VDD  -layer 36 -width 2.400 -pitch_within_group 11.640 -start_low_ends coordinate  -start_low_ends_coordinate 7.000 -start_high_ends coordinate  -start_high_ends_coordinate 353.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
